name: wassword
description: Wassword - Wonderful Password Generator

version: 2.4.0+24

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_styled_toast: ^2.2.1
  go_router: ^11.0.0
  google_fonts: ^6.1.0
  package_info_plus: ^4.1.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  window_manager: ^0.3.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icona/
