name: wassword
description: Wassword - Wonderful Password Generator

version: 2.4.0+24

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  fluttertoast: ^8.1.2
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  share_plus: ^6.3.0
  url_launcher: ^6.1.7
  window_manager: ^0.2.8

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icona/
