name: wassword
description: Wassword - Wonderful Password Generator

version: 2.1.3+17

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  fluttertoast: ^8.0.8
  go_router: ^2.5.0
  google_fonts: ^2.1.0
  share_plus: ^3.0.4
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icona/
