name: wassword
description: Wassword - Wonderful Password Generator

version: 2.3.0+23

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  go_router: ^3.1.0
  google_fonts: ^2.3.2
  share_plus: ^4.0.4
  url_launcher: ^6.1.2
  window_manager: ^0.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.0+1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icona/
